### PR TITLE
Don't auto-scaffold

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Goes with https://github.com/Islandora-Devops/islandora-playbook/pull/147

# What does this Pull Request do?

Unregisters the scaffold scripts so they are no longer run every time we update.

# How should this be tested?

Set `drupal_composer_project_package: "islandora/drupal-project:dev-no-auto-scaffold"` in `group_vars/webserver/drupal.yml` and provision a server.

# Interested parties
@elizoller, @Islandora/8-x-committers

### CODE REVIEW

**Comment by elizoller** [comment]
I can't seem to point to this PR.
```
fatal: [default]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/composer", "create-project", "islandora/drupal-project:no-auto-scaffold", "/tmp/composer-project", "--prefer-dist", "--stability", "dev", "--no-interaction"], "delta": "0:00:00.352645", "end": "2020-01-23 15:35:01.282244", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2020-01-23 15:35:00.929599", "stderr": "\n                                                                                                  \n  [UnexpectedValueException]                                                                      \n  Could not parse version constraint no-auto-scaffold: Invalid version string \"no-auto-scaffold\"  \n                                                                                                  \n\ncreate-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]", "stderr_lines": ["", "                                                                                                  ", "  [UnexpectedValueException]                                                                      ", "  Could not parse version constraint no-auto-scaffold: Invalid version string \"no-auto-scaffold\"  ", "                                                                                                  ", "", "create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]"], "stdout": "", "stdout_lines": []}
```

**Comment by elizoller** [comment]
"no-auto-scaffold" is an invalid version?

**Comment by dannylamb** [comment]
I think we may still need this for https://github.com/Islandora-Devops/islandora-playbook/pull/177

**Comment by whikloj** [comment]
I needed change the owner of `sites/default/default.settings.yml` and `sites/default/default.services.yml` from `root` to `vagrant`, but otherwise I could install something.

**Comment by dannylamb** [comment]
@whikloj I can update those in the playbook

**Comment by whikloj** [comment]
It is more of an implementation detail, I think it is worth considering but was not a deal breaker. Just wanted to note it incase anyone mentioned it.

**Comment by dannylamb** [comment]
Eh it's all related.  I'd prefer to take care of it now.  This permissions thing has been around for long enough.  Not being able to composer require out of the box is a pretty :hankey: user/dev experience.

**Pull request closed without merging**
