### PR TITLE
Rebasing off upstream project

### PR DESCRIPTION
**Pull request by dannylamb**

### CODE REVIEW

**Comment by dannylamb** [comment]
Resolves https://github.com/Islandora-CLAW/CLAW/issues/521

**Comment by DiegoPino** [comment]
@dannylamb sorry for being picky, but for would it not be cleaner to just make a small pull to .gitignore?
It is basically just a single line and the history will look a lot better. Thanks

**Comment by DiegoPino** [comment]
@ruebot that is what I'm asking, the commit from  https://github.com/drupal-composer/drupal-project  is just this line, a single change
https://github.com/Islandora-CLAW/drupal-project/pull/5/files#diff-a084b794bc0759e7a6b77810e01874f2R8

All the rest is a rebasing of our own module, and recommiting what we already have. 
Thanks

**Comment by jonathangreen** [comment]
@DiegoPino won't doing that just make the next rebase we have to do more messy since those commits are not in our history? We will likely need to continue to rebase in the future.

**Comment by DiegoPino** [comment]
@jonathangreen ok, if rebasing in the future is a concern, then my wrong, go ahead and merge. 
 I thought this was a fork that would eventually diverge a lot. Rebasing in the future, considering how custom our composer.json can get and what other exceptions we could end adding here could eventually end being an almost manual operation anyway. Like readding our changes, if we keep the parent history alive, since i can't imagine drupal-composer making islandora aware decisions or putting future dependencies always in the same spot.

**Comment by whikloj** [comment]
Based on this discussion it does raise the question of do we now need to maintain this branch ad infinitum? Could we have a skeleton composer.json that depends on the drupal-project and executes the same functions? Just so we don't have to keep rebasing as they make changes, we could just update versions?

**Pull request merged**
