### PR TITLE
Force Drush 9

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Related to Islandora/islandora_defaults#26 and maybe Islandora/islandora#764

# What does this Pull Request do?

When we recently pullled from upstream we got 9 | 10, so travis is now getting drush 10. This PR specifically pins us to 9.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by dannylamb** [comment]
Gonna need a blind merge on this one to fix the travis build.  @seth-shaw-unlv or @whikloj ?

**Comment by dannylamb** [comment]
For verification that this works, see https://github.com/Islandora/islandora_defaults/pull/28, which points at this branch.

**Review by seth-shaw-unlv — APPROVED** [review]
Blindly approving.

**Comment by dannylamb** [comment]
:bowing_man:

**Comment by seth-shaw-unlv** [comment]
Ah. Won't let me merge.

**Comment by seth-shaw-unlv** [comment]
Running checks again.

**Comment by dannylamb** [comment]
@seth-shaw-unlv drupal-project is failing, so does upstream :disappointed:

**Pull request merged**
