### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by manez**
**GitHub Issue**: https://github.com/Islandora/documentation/issues/1588

# What does this Pull Request do?

Adds mention of the new User Call to CONTRIBUTING.md.

# How should this be tested?

Preview & review

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Review by rosiel — APPROVED** [review]

**Comment by rosiel** [comment]
ugh, got bit by Travis. 

> PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///home/travis/.phpenv/versions/7.2.33/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

**Comment by manez** [comment]
I've restarted Travis a couple of times to the same results

**Comment by dannylamb** [comment]
Finally circling back around to this one.  Looks like maybe updating how we call composer a la https://github.com/Islandora/documentation/blob/master/.scripts/travis_setup_drupal.sh#L13 should work?

**Comment by dannylamb** [comment]
As it stands now, this PR is completely unrelated to the Travis issues, so I'm cool with @rosiel merging it in and we deal with it in a separate PR.

**Pull request merged**
