### PR TITLE
Adding Islandora dependencies

### PR DESCRIPTION
**Pull request by dannylamb**
Part of Islandora-CLAW/CLAW#474

### CODE REVIEW

**Comment by DiegoPino** [comment]
@dannylamb https://github.com/dannylamb/* ?

**Comment by dannylamb** [comment]
@DiegoPino  Yeah, bit of a chicken and egg sort of thing.  Figured I'd leave it pointing at my forks until PRs get merged in, and then update to point to the CLAW org repos with the appropriate branches.

I can make it point to the CLAW org now if you'd like.  It will make testing the install a bit trickier, though.

**Comment by DiegoPino** [comment]
@dannylamb i know, testing will be a pain, sorry, but i would prefer a cleaner history on that and point straight to CLAW org. Also depends on who will be testing

**Comment by dannylamb** [comment]
@DiegoPino Perhaps you would be doing some testing?

**Comment by DiegoPino** [comment]
@dannylamb in that case i have no issues with weird testing procedures. so claw org repos are fine 😄

**Comment by whikloj** [comment]
Do we need the claw-jsonld repository added as a dependency?

**Comment by dannylamb** [comment]
@whikloj The core islandora module pulls that in.

**Comment by dannylamb** [comment]
@whikloj @DiegoPino I'm thinking about closing this PR and issuing it against an 8.x-1.x branch to distinguish our work / protect the drupal community branch.

**Comment by dannylamb** [comment]
@whikloj @DiegoPino this has been replaced with #2

**Pull request closed without merging**
