### PR TITLE
Update to Drupal 8.8.1

### PR DESCRIPTION
**Pull request by elizoller**
# What does this Pull Request do?
This might be a bit bold but... I tested Drupal 8.8.1 (by updating composer packages) and it seemed to go ok, so here is my attempt at updating it the proper way.

# What's new?
* An updated composer.json which includes drupal/core 8.8.1 and drupal/core-dev 8.8.1 (replaces webflo/drupal-core-require-dev which is deprecated)
* An updated composer.lock

# How should this be tested?
Point a playbook at this branch in inventory/vagrant/group_vars/webserver/drupal.yml `drupal_composer_project_package` (not exactly sure how to point it to a PR instead of a release)

# Additional Notes:
I'm not sure if this is the right approach, but I thought I'd just put this out there to hopefully get the ball rolling.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by elizoller** [comment]
@qadan brought up an issue related to pathauto and path_alias https://www.drupal.org/project/drupal/releases/8.8.0 
i'm not sure if/how we're using those modules in islandora default things and/or how it relates to https://github.com/Islandora/documentation/issues/1095

**Comment by dannylamb** [comment]
We're not doing anything with it _per se_, but there may be folks out there with path auto set up and would have to be careful when upgrading.  But they'd be doing that manually and not through the initial composer install, so I think it's good to move ahead with this sooner rather than later.

**Comment by dannylamb** [comment]
@elizoller We don't commit the lockfile here.  You would on your own project, but it messes with the installer (can't recall exactly why).

Also, tests are failing but that's got nothing to do with what you're doing.  Can you pull in changes from upstream to see if it fixes it?

**Review by dannylamb — DISMISSED** [review]
^^

**Comment by elizoller** [comment]
pull in the changes from drupal-composer/drupal-project or islandora/drupal-project?

**Review by dannylamb — CHANGES_REQUESTED** [review]
^^

**Comment by dannylamb** [comment]
@elizoller From drupal-composer/drupal-project

**Comment by dannylamb** [comment]
Nice @elizoller, tests are passing.  Can you remove the lockfile and I'll merge this in?

**Comment by elizoller** [comment]
composer.lock should be deleted in this PR. although it is there in the main 8.x-1.x branch at https://github.com/Islandora/drupal-project

**Comment by dannylamb** [comment]
:man_facepalming: I see that now @elizoller.  There was a diff... a diff that was all red...

We've historically not included it, and it's not in drupal-composer/drupal-project.  But history shows I accidentally committed it back in :(

**Review by dannylamb — APPROVED** [review]

**Comment by dannylamb** [comment]
Sry for the confusion @elizoller.  Thanks for this!

**Pull request merged**
