### PR TITLE
update travis badge

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Islandora-CLAW/CLAW#950

# What does this Pull Request do?

Grabs the travis badge from travis-ci.com instead of travis-ci.org

# Interested parties
@Islandora-CLAW/committers

_Please delete branch after merging_

### CODE REVIEW

**Comment by whikloj** [comment]
@dannylamb not sure what to say. Does this include our requirements somewhere? We just use this to pin the version right?

**Comment by dannylamb** [comment]
@whikloj At this point it is exclusively just to pin down a version of drupal core.  Should we even bother?

**Comment by whikloj** [comment]
I'm not clear on why 5.6 is failing then, the base drupal-composer/drupal-project passed a 5.6 build yesterday. Do we include something special in ours?

**Comment by DiegoPino** [comment]
@dannylamb @whikloj the composer lock file points to package versions that are PHP 7 only, like 

```
"name": "doctrine/inflector",
"version": "v1.2.0"
```

Even when you do a composer install, the drupal-composer project runs a pre-validate against the lock
`Installing dependencies (including require-dev) from lock file`

IMHO, probably better to burn PHP 5.6 or keep 2 branches with different locks, or give it a try without the lock so it has to re-resolve all based on the main PHP.

**Comment by whikloj** [comment]
So the options here are to provide a composer lock file built with php 5.6 or stop testing for 5.6.

I'm good either way, while Drupal 8 supports 5.6 CLAW will not so we can remove that test.

**Comment by dannylamb** [comment]
yeah let's just drop 5.6

**Review by whikloj — APPROVED** [review]
👍

**Pull request merged**
