### PR TITLE
Getting rid of drupal console for composer 2 compatibility

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Needed for https://github.com/Islandora/islandora/pull/806

# What does this Pull Request do?

Pull drupal console from our composer.json since it's not a hard dependency and fails with composer 2.

# How should this be tested?

It's already tested b/c Travis is happy with https://github.com/Islandora/islandora/pull/806

# Additional Notes:
After this is merged, I'll update https://github.com/Islandora/islandora/pull/806 to pull from 8.x-1.x.  Hopefully this unlocks the rest of the repos for Travis.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
I get the feeling, @dannylamb, that Travis _shouldn't_ be red...

**Comment by dannylamb** [comment]
Every step of the way, y'know?

**Comment by dannylamb** [comment]
I've been getting queued by Travis a lot lately so this may take some time.  But I _think_ I've fixed the current issue with Travis.

**Comment by dannylamb** [comment]
...and so the scaffolding _does_ rely on drupal console apparantly? Hard to tell from the output.  If I can't pull a rabbit out of my hat we may have to consider finally moving to `drupal/recommended-project` instead.

**Comment by dannylamb** [comment]
Whelp, the `snapshot` builds fail.  The internet tells me to update composer based on the error message I'm receiving.  But by definition, `snapshot` means newest, so... I put those build as allowed failures and am moving on.  Testing with bleeding edge composer doesn't seem like a required pass to me.

**Comment by dannylamb** [comment]
I think I've finally got this going @seth-shaw-unlv

**Comment by seth-shaw-unlv** [comment]
Getting the kids lunch right now, but I'll glance at it when I get back to my desk.

**Review by seth-shaw-unlv — APPROVED** [review]
👍

**Pull request merged**
