### PR TITLE
New lockfile to bump drupal version

### PR DESCRIPTION
**Pull request by dannylamb**
Resolves https://github.com/Islandora-CLAW/CLAW/issues/1034

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
@dannylamb Travis is grumpy.

**Comment by seth-shaw-unlv** [comment]
Trying to test this but composer doesn't seem to like how I configured claw-playbook.

I updated drupal.yml in my vagrant inventory so that: `drupal_composer_project_package: "dannylamb/drupal-project:dev-drupal-version-bump"` but ansible comes back and complains: ` Could not find package dannylamb/drupal-project with version dev-drupal-version-bump.` Removing "dev-" didn't help.

How should I configure my playbook so that it sees this, @dannylamb? Is there a flag I need to add to `drupal_composer_project_options`?

**Comment by whikloj** [comment]
I tried this as well, I think it needs a packagist package. @dannylamb maybe if you could make this as a branch on Islandora-CLAW/drupal-project we could pull it in then 🤷‍♂️

**Comment by dannylamb** [comment]
k, getting into a weird rebase scenario here but I'll make another PR from a branch on origin

**Comment by dannylamb** [comment]
Superseded by https://github.com/Islandora-CLAW/drupal-project/pull/26

**Pull request closed without merging**
