### PR TITLE
New lockfile to bump drupal version

### PR DESCRIPTION
**Pull request by dannylamb**
Resolves https://github.com/Islandora-CLAW/CLAW/issues/1034

Supersedes https://github.com/Islandora-CLAW/drupal-project/pull/25

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
@dannylamb  Not sure why, but this PR breaks drush cset for drupal-openseadragon:
```
TASK [Islandora-Devops.drupal-openseadragon : Set IIIF URL] ********************
Monday 25 February 2019  13:47:36 -0800 (0:00:00.443)       0:12:54.242 ******* 
fatal: [default]: FAILED! => {"changed": true, "cmd": ["/var/www/html/drupal/vendor/drush/drush/drush", "cset", "openseadragon.settings", "iiif_server", "http://localhost:8080/cantaloupe/iiif/2", "--yes"], "delta": "0:00:00.103556", "end": "2019-02-25 21:47:36.066005", "msg": "non-zero return code", "rc": 1, "start": "2019-02-25 21:47:35.962449", "stderr": "\n                                                                               \n  Command cset was not found. Pass --root or a @siteAlias in order to run Dru  \n  pal-specific commands.                                                       \n                                                                               ", "stderr_lines": ["", "                                                                               ", "  Command cset was not found. Pass --root or a @siteAlias in order to run Dru  ", "  pal-specific commands.                                                       ", "                                                                               "], "stdout": "", "stdout_lines": []}
```
I tried it twice with the PR applied, and it failed the same way, reverted back and it was fine.

**Comment by whikloj** [comment]
@seth-shaw-unlv probably the parameters have changed with the drupal version, we'll need to actually try this to see what is correct now.

**Comment by dannylamb** [comment]
Getting deprecation warnings in Travis. That's a pretty easy fix I think.

**Comment by dannylamb** [comment]
Looking at this now I can't even tell which tests are getting run.  And the supposedly easy `--suppress-deprecation-warnings` flag I was thinking of is part of drupal's `scripts` directory, not `phpuit`. :(

**Comment by dannylamb** [comment]
Oh this is painful.  Remove the deprecation warnings, and now tests that are expecting the deprecation warnings fail....  C'mon.

**Comment by whikloj** [comment]
So this is dying on openseadragon as @seth-shaw-unlv saw before.

It appears that we are not in the correct directory to check the IIIF server or set it. The first fails (but that is allowed), but then the second can't execute.

If I `vagrant ssh` into the box and run the same command from `/var/www/html/drupal/web` it works.

**Comment by seth-shaw-unlv** [comment]
So we can either add a "cd" task OR we can add the site uri flag (i.e. `
/var/www/html/drupal/vendor/drush/drush/drush --uri http://localhost:8000 cset openseadragon.settings iiif_server http://localhost:8080/cantaloupe/iiif/2 --yes`).

**Comment by whikloj** [comment]
We have the `chdir` argument which should be changing us to that directory. I feel like maybe something else is happening to cause this change now.

**Comment by seth-shaw-unlv** [comment]
~~@whikloj it all of a sudden started working. I added some debug messages to the playbook to see what was going on and it worked fine. Surprised that it worked, I deleted the external role directory to try again, and it worked again. Can you try again and verify?~~
NM, somehow I had reverted to the current drupal-project, not the PR...

**Comment by whikloj** [comment]
Adding `--root {{ openseadragon_composer_root }}/web` to the drush calls fixed the openseadragon tasks and then I fail at the "Uninstall core search module" task.

So I feel like this change also will require changes to all the various roles. I'll create a PR with the changes I made to the ansible-role-openseadragon.

**Comment by seth-shaw-unlv** [comment]
I wonder if this is due to the composer lock file's [Drush version bump to 9.5.2](https://github.com/Islandora-CLAW/drupal-project/pull/26/files#diff-1da2c7edc898c70e5a79a9997c98ceccR2108)...

**Comment by whikloj** [comment]
@seth-shaw-unlv yeah that might be it.

**Comment by dannylamb** [comment]
I'm going to kick off the tests again to see what's up now that https://github.com/Islandora-Devops/ansible-role-drupal-openseadragon/pull/5 has landed.  [drupal-project builds are also failing](https://travis-ci.org/drupal-composer/drupal-project), and I don't think my changes with suppressing deprecation warnings was beneficial.  It appears some of the tests are actually expecting the deprecation warnings and handling them appropriately. 

So we'll see.  If it's still busted I'll probably just revert those changes so we can more cleanly pull in from upstream whenever things get sorted out.

**Comment by dannylamb** [comment]
@whikloj Ok, i've reverted the half-baked attempt to fix tests and we just have the lockfile.

**Pull request merged**
