### PR TITLE
Drupal 8.7

### PR DESCRIPTION
**Pull request by Natkeeran**
Ticket: https://github.com/Islandora-CLAW/CLAW/issues/1110

This is the first time I am doing this, so please do review it carefully.

## What's new?
* merged it with upstream
* `sudo composer update` in my own machine

## How should this be tested?
* Cone the latest claw-playbook
* Edit [this line](https://github.com/Islandora-Devops/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml#L20) to point to this branch (`drupal_composer_project_package: "islandora/drupal-project:dev-drupal_87"`)
* vagrant up
* verify that the red error message we used to get no longer shows!
* Verify Drupl 8.7 is installed - http://localhost:8000/admin/reports/status
* Do basic Islandora sanity checks - (i.e create new objects and verify derivatives are created, synched properly)

@Islandora-CLAW/committers

### CODE REVIEW

**Comment by whikloj** [comment]
👀

**Comment by whikloj** [comment]
Looking good so far
```
TASK [Install demo module (fail ok)] *******************************************
Thursday 23 May 2019  16:57:47 -0500 (0:00:00.714)       0:23:02.463 ********** 
changed: [default]

TASK [Update entities] *********************************************************
```

**Comment by whikloj** [comment]
@Islandora-CLAW/committers 
So this seems to work to get us to Drupal 8.7, except the glorious devs they have seen fit to save us from ourselves again.

Previously you would go to `http://localhost:8080/media/1` but now the Media content tab links are all to the edit page. ie `http://localhost:8000/media/1/edit` and the old media page returns a 404 page not found.

Apparently this was considered a security risk. Currently you can re-enable the canonical route via a switch in the **Media Settings** configuration (`admin/config/media/media-settings`).

https://www.drupal.org/project/drupal/issues/3017935

I have [asked on the ticket](https://www.drupal.org/project/drupal/issues/3017935#comment-13119278) that caused this joy what the Drupal core long term plan is for media entities, I'll see what they say.

So we will need to force the enabling of this checkbox. 

**BUT** also the `/media/{id}` path is gone from the REST interface, it is now `/media/{id}/edit`.

So the upgrade to 8.7 will require some serious changes.

 Long live Drupal, may its horror rain down upon us always

**Comment by Natkeeran** [comment]
@whikloj @dannylamb 

They have replied.  It appears the scope is just to make this configurable.  

I suppose the implication of enabling the setting is that media in draft mode can be exposed via URL for users with media view permission.

**Comment by dannylamb** [comment]
Nothing like some last minute fun, eh?  I'm `vagrant up`ing to find the full extent the breakage and whether or not we want to adopt this behaviour of hiding the media canonical url (why didn't they just change around permissions instead?).

For now though, just setting that variable with ansible will keep us going.

**Comment by whikloj** [comment]
@Natkeeran yes it appears that the concern (which is valid) is that any user with a `View Media` permission can then view any media.

I have added a second question about the change in the REST endpoint to that Drupal ticket.

I would vote against pushing for 8.7 for Islandora 8's release as I might have missed some other things not working while fighting through these issues.

But merge and tagging this change would open the door to working with Drupal 8.7 within the Islandora 8 structure after the 1.0.0 release.

**Review by whikloj — APPROVED** [review]
👍 works as expected, dev branch testing failed last time too but stable succeeds

**Pull request merged**
